### PR TITLE
added architectui.com

### LINKED ISSUE #2373: Sparkling Resource: architectUI.com
Hello @mdo , great job on Bootstrap :)

I've made a ReactJS Bootstrap 4 Dashboard Theme. Include it maybe in the Expo? 

demo at: https://demo.architectui.com/default

Thanks,
Horia

Ps. Keep up the good work

### PR DESCRIPTION
**Pull request by architectdev**
Fixes #2373

### CODE REVIEW

**Comment by XhmikosR** [comment]
@architectdev: the image isn't optimized properly.

**Comment by XhmikosR** [comment]
architectui

`jpegoptim -s foo.jpg`

**Comment by architectdev** [comment]
@XhmikosR Fixed!

**Comment by XhmikosR** [comment]
Please use this image, or run `jpegoptim -s` yourself.

architectui

**Comment by architectdev** [comment]
@XhmikosR thanks for that. Updated

**Pull request merged**
