### PR TITLE
adding uifort.com

### PR DESCRIPTION
**Pull request by uifortdev**
@XhmikosR @mdo @dhg

Hey guys, I really think that my project shows just how powerful Bootstrap is! Check out what I've built entirely with Bootstrap here: https://uifort.com

It would be great if you could add it to the expo section.

### CODE REVIEW

**Comment by uifortdev** [comment]
Hey guys, any updates on this?

**Comment by XhmikosR** [comment]
Please be patient. @dhg will take care of it when he has time.

**Comment by uifortdev** [comment]
Thank you.

**Comment by architectdev** [comment]
@XhmikosR @mdo @dhg any updates on this?

**Comment by uifortdev** [comment]
@XhmikosR @mdo @dhg any updates on this?

**Comment by dhg** [comment]
Hey @uifortdev – Unfortunately at this time we won't be able to accept the site. We're focused on sites with beautiful designs that are powered by Bootstrap, not Bootstrap themes or marketplaces. Best of luck with the site though!

**Comment by uifortdev** [comment]
> Hey @uifortdev – Unfortunately at this time we won't be able to accept the site. We're focused on sites with beautiful designs that are powered by Bootstrap, not Bootstrap themes or marketplaces. Best of luck with the site though!

I was submitting it because of it's beautiful design and clean codebase and because it's powered by Bootstrap, not because it's a marketplace for themes...

Also, you guys accepted one of my old websites in the expo back in december 2018, which also features themes & templates...

**Pull request closed without merging**
