### PR TITLE
Adding dashboardpack.com

### PR DESCRIPTION
**Pull request by dpackdev**
cc @XhmikosR Thanks!

### CODE REVIEW

**Comment by dpackdev** [comment]
Thanks, if the pull request has been approved, does that mean that it will get merged?

**Comment by XhmikosR** [comment]
I can't tell you that yet.

/CC @dhg

**Comment by dhg** [comment]
Hey @dpackdev – Thanks for tackling the code side of things yourself :) That's awesome. We have a list of sites to review right now, but are working on a process for all this, so please hold tight and we'll get back to you soon!

**Comment by dpackdev** [comment]
> Hey @dpackdev – Thanks for tackling the code side of things yourself :) That's awesome. We have a list of sites to review right now, but are working on a process for all this, so please hold tight and we'll get back to you soon!

Oh ok, i understand. It seems that these days almost all doors you knock on are closed or closing :)

Anyway, thank you guys for the replies, appreciate it!

**Pull request closed without merging**
